### PR TITLE
Feature operating system

### PR DESCRIPTION
**Pull request by MiConnell**
This is a cool project!
I added some functionality for mac users and it worked with some (limited) testing on my machine.
I don't think much changed for the Windows functionality but please test before merging if you're going to since I don't have a Windows machine to test on.

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Looks good, but a lot of code is repeated.
The os.path.join() works for all operating systems.
So checking operating system is redundant.
Maybe keep the os.path.join() and remove the operating system check conditionals

**Review by ghost — CHANGES_REQUESTED** [review]
Or you could do something like this

just pseudocode
if os == 'Darwin':
    drive = os.path.expanduser(drive)
elif os=='Windows':
    drive = drive + '\\'
else:
     os not supported
     return

and the rest of the code is common for both windows and mac
os.path.join() works for both

**Comment by MiConnell** [comment]
Oh yeah...
Ok I simplified the logic for your review.

**Comment by piyx** [comment]
Great! I merged it! I also added few of you previous code to it.
I think you misunderstood me, I actually wanted you to keep the os.path.join().
Anyways I added that back. Great work.
Could you try the updated code once on your machine and see if it works, if not please do make the required changes.

**Pull request merged**
